#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "itflow"
name = "ITFlow"
description.en = "IT documentation, ticketing and accounting system for small MSPs"
description.fr = "Système de documentation, de billetterie et de comptabilité pour les petits MSP"

version = "25.12~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0"
website = "https://itflow.org/"
demo = "https://demo.itflow.org/"
admindoc = "https://docs.itflow.org/installation"
code = "https://github.com/itflow-org/itflow"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr_FR", "en_US"]
    default = "fr_FR"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

    [install.company_name]
    ask.en = "Choose the company name"
    ask.fr = "Choisissez le nom de l'entreprise"
    type = "string"

    [install.address]
    ask.en = "Choose the company address"
    ask.fr = "Choisissez l'adresse de l'entreprise"
    type = "string"

    [install.city]
        ask.en = "Choose the company city"
    type = "string"
    
    [install.state]
    ask.en = "Choose the company state"
    ask.fr = "Choisissez la ville de l'entreprise"
    type = "string"
    
    [install.zip]
    ask.en = "Choose the company zip code"
    ask.fr = "Choisissez le code postal de l'entreprise"
    type = "string"
    
    [install.country]
    ask.en = "Choose the company country"
    ask.fr = "Choisissez le pays de l'entreprise"
    type = "string"

    [install.phone]
    ask.en = "Choose the company phone number"
    ask.fr = "Choisissez le numéro de téléphone de l'entreprise"
    type = "string"
    
    [install.company_email]
    ask.en = "Choose the company email"
    ask.fr = "Choisissez l'adresse e-mail de l'entreprise"
    type = "string"
    
    [install.website]
    ask.en = "Choose the company website"
    ask.fr = "Choisissez le site Web de l'entreprise"
    type = "string"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/itflow-org/itflow/archive/refs/tags/v25.12.tar.gz"
    sha256 = "d735ce7c977e14149a3714290bef2e360b9a2135e476ebfbaf61470820319215"

    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.3-intl, php8.3-gd, php8.3-imap, php8.3-mailparse, php8.3-mysqli, php8.3-curl, php8.3-xml"

    [resources.database]
    type = "mysql"
