#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "itflow"
name = "ITFlow"
description.en = "IT documentation, ticketing and accounting system for small MSPs"
description.fr = "Système de documentation, de billetterie et de comptabilité pour les petits MSP"

version = "2025.04.18~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0"
website = "https://itflow.org/"
demo = "https://demo.itflow.org/"
admindoc = "https://docs.itflow.org/installation"
code = "https://github.com/itflow-org/itflow"

[integration]
yunohost = ">= 11.2.29"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/itflow"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/itflow-org/itflow/archive/b69a70cfc31b2841486c3cf49de69ef8ba3ed808.tar.gz"
    sha256 = "1b469b9db93019388f2251473685933da3a0b019b1a90fc984148d1ed695a568"
    autoupdate.upstream = "https://github.com/itflow-org/itflow"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.2-intl, php8.2-imap, php8.2-mailparse, php8.2-mysqli, php8.2-curl, mariadb-server"

    [resources.database]
    type = "mysql"
