#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "itflow"
name = "ITFlow"
description.en = "IT documentation, ticketing and accounting system for small MSPs"
description.fr = "Système de documentation, de billetterie et de comptabilité pour les petits MSP"

version = "2025.12.04~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0"
website = "https://itflow.org/"
demo = "https://demo.itflow.org/"
admindoc = "https://docs.itflow.org/installation"
code = "https://github.com/itflow-org/itflow"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/itflow-org/itflow/archive/c7ef3627ce7cab0454f3c5d42df6f77c9b67be7c.tar.gz"
    sha256 = "ffe2a6c9c0a8646cb5c6068b2961906ec7d50b0063d9a1faced7f7d27c336c9f"
    autoupdate.upstream = "https://github.com/itflow-org/itflow"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.2-intl, php8.2-imap, php8.2-mailparse, php8.2-mysqli, php8.2-curl"

    [resources.database]
    type = "mysql"
