#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "itflow"
name = "ITFlow"
description.en = "IT documentation, ticketing and accounting system for small MSPs"
description.fr = "Système de documentation, de billetterie et de comptabilité pour les petits MSP"

version = "2025.12.06~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0"
website = "https://itflow.org/"
demo = "https://demo.itflow.org/"
admindoc = "https://docs.itflow.org/installation"
code = "https://github.com/itflow-org/itflow"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr_FR", "en_US"]
    default = "fr_FR"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/itflow-org/itflow/archive/03570ecd049551619c9be0c0e842eb9d058e6bac.tar.gz"
    sha256 = "2936a1735fe22267023cb72568853d6845f4d7a6ef5844959cf263f838986584"
    autoupdate.upstream = "https://github.com/itflow-org/itflow"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.3-intl, php8.3-gd, php8.3-imap, php8.3-mailparse, php8.3-mysqli, php8.3-curl"

    [resources.database]
    type = "mysql"
