#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set --key=php_upload_max_filesize --value=500M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

#=================================================
# INSTALL THE DATABASE
#=================================================
ynh_script_progression "Installing $app..."

pushd "$install_dir"
	php$php_version setup_cli.php --host="localhost" --database="$db_name" --password="$db_pwd" --username="$db_user" \
	--base-url=$domain$path \
	--locale=fr_FR \
	--currency=EUR \
	--company-name=YunoHost \
	--country=France \
	--user-name=$admin \
	--user-email=$email \
	--user-password=$password\
	--non-interactive
popd

chown -R $app:www-data "$install_dir"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
