#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

ynh_app_setting_set_default --key=php_upload_max_filesize --value=500M
ynh_app_setting_set_default --key=php_post_max_size --value=500M

email=$(ynh_user_get_info --username=$admin --key=mail)

timezone="$(cat /etc/timezone)"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

#=================================================
# INSTALL THE DATABASE
#=================================================
ynh_script_progression "Installing $app..."

pushd "$install_dir/scripts"
	php$php_version setup_cli.php --host="localhost" --username="$db_user" --password="$db_pwd" --database="$db_name"  \
		--base-url="$domain$path" --locale="$language" --timezone="$timezone" --currency="EUR" \
		--company-name="YunoHost" --country="France" --user-name="$admin" --user-email="$email" --user-password="$password" \
    	--address="1 rue essai" --city="Paris" --state="france" --zip="75001" --phone="0123456789" --company-email="$email" --website="www.essai.com" \
		--non-interactive
popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
